[buildPlans.iosevka-custom]
family = "Iosevka Custom"
spacing = "fontconfig-mono"
serifs = "sans"
no-cv-ss = false

[buildPlans.iosevka-custom.variants.design]
i = "diagonal-tailed"
j = "diagonal-tailed-serifless"
k = "curly-serifless"
l = "diagonal-tailed"
t = "diagonal-tailed-short-neck"
lower-lambda = "straight-turn"
asterisk = "turn-hex-high"
brace = "curly-flat-boundary"
ampersand = "lower-open"
dollar = "open"
percent = "rings-continuous-slash-also-connected"
lig-ltgteq = "slanted"
